name: Mirror Repository

on: push

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Git
      run: |
        git config --global user.name "Tanaton.phuk"
        git config --global user.email "fifa52766@gmail.com"

    - name: Push to mirror repository
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git remote add mirror https://${{ secrets.PAT_TOKEN }}@github.com/ICAREU/mirror-icareu.git
        git push --mirror mirror
